interface JobMatchData {
  jobTitle: string;
  companyName?: string;
  matchPercentage: number;
  matchedSkills: string[];
  missingSkills: Array<{ skill: string; priority: string }>;
  bonusSkills: string[];
  summary: string;
  projectMappings?: Array<{
    projectName: string;
    matchedSkills: string[];
    relevanceScore: number;
  }>;
}

export function generateJobMatchText(data: JobMatchData): string {
  const lines: string[] = [];

  lines.push("=".repeat(60));
  lines.push("JOB MATCH ANALYSIS REPORT");
  lines.push("=".repeat(60));
  lines.push("");

  lines.push(`Position: ${data.jobTitle}`);
  if (data.companyName) {
    lines.push(`Company: ${data.companyName}`);
  }
  lines.push(`Match Score: ${data.matchPercentage}%`);
  lines.push(`Generated: ${new Date().toLocaleDateString()}`);
  lines.push("");

  lines.push("-".repeat(60));
  lines.push("SUMMARY");
  lines.push("-".repeat(60));
  lines.push(data.summary);
  lines.push("");

  if (data.matchedSkills.length > 0) {
    lines.push("-".repeat(60));
    lines.push(`MATCHED SKILLS (${data.matchedSkills.length})`);
    lines.push("-".repeat(60));
    data.matchedSkills.forEach((skill) => {
      lines.push(`✓ ${skill}`);
    });
    lines.push("");
  }

  if (data.missingSkills.length > 0) {
    lines.push("-".repeat(60));
    lines.push(`SKILLS TO DEVELOP (${data.missingSkills.length})`);
    lines.push("-".repeat(60));
    data.missingSkills.forEach((item) => {
      const priority = item.priority.toUpperCase();
      lines.push(`○ ${item.skill} [${priority} PRIORITY]`);
    });
    lines.push("");
  }

  if (data.bonusSkills.length > 0) {
    lines.push("-".repeat(60));
    lines.push(`BONUS SKILLS (${data.bonusSkills.length})`);
    lines.push("-".repeat(60));
    data.bonusSkills.forEach((skill) => {
      lines.push(`★ ${skill}`);
    });
    lines.push("");
  }

  if (data.projectMappings && data.projectMappings.length > 0) {
    lines.push("-".repeat(60));
    lines.push("RELEVANT PROJECTS");
    lines.push("-".repeat(60));
    data.projectMappings
      .sort((a, b) => b.relevanceScore - a.relevanceScore)
      .forEach((project) => {
        lines.push(
          `\n${project.projectName} (${project.relevanceScore}% relevant)`
        );
        lines.push(`  Skills: ${project.matchedSkills.join(", ")}`);
      });
    lines.push("");
  }

  lines.push("-".repeat(60));
  lines.push("Generated by CodeCraft - AI-Powered Career Readiness Platform");
  lines.push("https://codecraft.app");
  lines.push("-".repeat(60));

  return lines.join("\n");
}

export function downloadJobMatchReport(data: JobMatchData) {
  const text = generateJobMatchText(data);
  const blob = new Blob([text], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `job-match-${data.jobTitle.replace(/\s+/g, "-").toLowerCase()}-${Date.now()}.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function copyJobMatchToClipboard(data: JobMatchData): Promise<void> {
  const text = generateJobMatchText(data);
  return navigator.clipboard.writeText(text);
}
