import type { Metadata } from "next";
import { AuthContextProvider } from "@/lib/auth/AuthProvider";
import { Newsreader, DM_Sans, Caveat } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";

const newsreader = Newsreader({
  subsets: ["latin"],
  variable: "--font-newsreader",
  display: "swap",
});

const dmSans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-dm-sans",
  display: "swap",
});

const caveat = Caveat({
  subsets: ["latin"],
  variable: "--font-caveat",
  display: "swap",
});

export const metadata: Metadata = {
  title: "CodeCraft",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${newsreader.variable} ${dmSans.variable} ${caveat.variable}`}
    >
      <body className={dmSans.className}>
        <AuthContextProvider>
          <Toaster />
          <main>{children}</main>
        </AuthContextProvider>
      </body>
    </html>
  );
}
