import type { Metadata } from "next";
import { AuthContextProvider } from "@/lib/auth/AuthProvider";
import { Newsreader, Sansation } from "next/font/google";
import UserMenu from "@/components/UserMenu";
import "./globals.css";
import Link from "next/link";

const newsreader = Newsreader({
  style: ["normal"],
  variable: "--font-newsreader",
});

const sansation = Sansation({
  weight: "400",
  variable: "--font-sansation",
});

export const metadata: Metadata = {
  title: "CodeCraft",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${newsreader.className} ${sansation.className}`}
    >
      <body>
        <AuthContextProvider>
          <main>{children}</main>
        </AuthContextProvider>
      </body>
    </html>
  );
}
