import type { Metadata } from "next";
import { AuthContextProvider } from "@/lib/auth/AuthProvider";
import AutoLogoutProvider from "@/lib/auth/AutoLogoutProvider";
import { Newsreader, Sansation } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";

const newsreader = Newsreader({
  style: ["normal"],
  variable: "--font-newsreader",
});

const sansation = Sansation({
  weight: "400",
  variable: "--font-sansation",
});

export const metadata: Metadata = {
  title: "CodeCraft",
  description: "Generated by create next app",
  icons: {
    icon: "/icon-logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${newsreader.className} ${sansation.className}`}
    >
      <head>
        <link
          rel="preconnect"
          href="https://fonts.googleapis.com"
          crossOrigin="anonymous"
        />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200&display=block"
          media="all"
        />
      </head>
      <body>
        <AuthContextProvider>
          <AutoLogoutProvider
            inactivityTimeout={30 * 60 * 1000}
            warningTime={5 * 60 * 1000}
          >
            <Toaster />
            <main>{children}</main>
          </AutoLogoutProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
