import type { ProjectTemplate } from "@/types/recommendations";

/**
 * Fallback project templates used when external sources fail
 * These templates ensure users always receive recommendations
 * Covers different difficulty levels and categories
 */
export const FALLBACK_TEMPLATES: ProjectTemplate[] = [
  {
    id: "fallback-todo-app",
    name: "Task Management App",
    description:
      "Build a full-featured todo application with user authentication, task categories, and due dates. Learn CRUD operations, state management, and responsive design.",
    techStack: ["React", "TypeScript", "Tailwind CSS", "Supabase"],
    difficulty: "beginner",
    timeEstimate: "1-2 weeks",
    skillsTaught: [
      "React Hooks",
      "State Management",
      "Authentication",
      "Database Operations",
      "Responsive Design",
    ],
    category: "fullstack",
    features: [
      "User authentication and authorization",
      "Create, read, update, delete tasks",
      "Task categories and tags",
      "Due dates and reminders",
      "Filter and search functionality",
      "Responsive mobile-first design",
    ],
    learningResources: [
      {
        title: "React Official Tutorial",
        url: "https://react.dev/learn",
        type: "tutorial",
        provider: "React",
      },
      {
        title: "Supabase Authentication Guide",
        url: "https://supabase.com/docs/guides/auth",
        type: "docs",
        provider: "Supabase",
      },
    ],
  },
  {
    id: "fallback-rest-api",
    name: "RESTful API with Node.js",
    description:
      "Create a production-ready REST API with authentication, validation, error handling, and comprehensive testing. Perfect for learning backend fundamentals.",
    techStack: ["Node.js", "Express", "PostgreSQL", "JWT", "Jest"],
    difficulty: "intermediate",
    timeEstimate: "2-3 weeks",
    skillsTaught: [
      "API Design",
      "Authentication & Authorization",
      "Database Design",
      "Error Handling",
      "Testing",
      "Security Best Practices",
    ],
    category: "backend",
    features: [
      "JWT-based authentication",
      "Role-based access control",
      "Input validation and sanitization",
      "Comprehensive error handling",
      "Rate limiting and security headers",
      "Unit and integration tests",
      "API documentation with Swagger",
    ],
    learningResources: [
      {
        title: "Express.js Guide",
        url: "https://expressjs.com/en/guide/routing.html",
        type: "docs",
        provider: "Express",
      },
      {
        title: "REST API Best Practices",
        url: "https://www.freecodecamp.org/news/rest-api-best-practices/",
        type: "article",
        provider: "FreeCodeCamp",
      },
    ],
  },
  {
    id: "fallback-portfolio-site",
    name: "Developer Portfolio Website",
    description:
      "Design and build a stunning portfolio website to showcase your projects. Learn modern web design, animations, and SEO optimization.",
    techStack: ["Next.js", "TypeScript", "Tailwind CSS", "Framer Motion"],
    difficulty: "beginner",
    timeEstimate: "1 week",
    skillsTaught: [
      "Next.js App Router",
      "Server Components",
      "SEO Optimization",
      "Animations",
      "Responsive Design",
      "Performance Optimization",
    ],
    category: "frontend",
    features: [
      "Hero section with animations",
      "Project showcase with filtering",
      "About and skills sections",
      "Contact form with validation",
      "Blog with MDX support",
      "Dark mode toggle",
      "SEO meta tags and sitemap",
    ],
    learningResources: [
      {
        title: "Next.js Documentation",
        url: "https://nextjs.org/docs",
        type: "docs",
        provider: "Next.js",
      },
      {
        title: "Tailwind CSS Tutorial",
        url: "https://tailwindcss.com/docs",
        type: "docs",
        provider: "Tailwind",
      },
    ],
  },
  {
    id: "fallback-realtime-chat",
    name: "Real-time Chat Application",
    description:
      "Build a real-time chat app with WebSockets, typing indicators, and message history. Learn real-time communication and state synchronization.",
    techStack: ["React", "Socket.io", "Node.js", "MongoDB", "Redis"],
    difficulty: "advanced",
    timeEstimate: "3-4 weeks",
    skillsTaught: [
      "WebSocket Communication",
      "Real-time State Management",
      "Message Queuing",
      "Caching Strategies",
      "Scalability Patterns",
    ],
    category: "fullstack",
    features: [
      "Real-time messaging with Socket.io",
      "Private and group chats",
      "Typing indicators and read receipts",
      "Message history and search",
      "File sharing and image uploads",
      "User presence and status",
      "Message encryption",
    ],
    learningResources: [
      {
        title: "Socket.io Documentation",
        url: "https://socket.io/docs/v4/",
        type: "docs",
        provider: "Socket.io",
      },
      {
        title: "Building Real-time Apps",
        url: "https://www.freecodecamp.org/news/build-a-realtime-chat-app-with-react-express-socketio-and-harperdb/",
        type: "tutorial",
        provider: "FreeCodeCamp",
      },
    ],
  },
  {
    id: "fallback-ecommerce",
    name: "E-commerce Platform",
    description:
      "Create a full-featured e-commerce platform with product catalog, shopping cart, checkout, and payment integration. Learn complex state management and payment processing.",
    techStack: [
      "Next.js",
      "TypeScript",
      "Stripe",
      "PostgreSQL",
      "Prisma",
      "Zustand",
    ],
    difficulty: "advanced",
    timeEstimate: "4-6 weeks",
    skillsTaught: [
      "Payment Integration",
      "Complex State Management",
      "Database Relationships",
      "Order Processing",
      "Inventory Management",
      "Email Notifications",
    ],
    category: "fullstack",
    features: [
      "Product catalog with search and filters",
      "Shopping cart with persistence",
      "Stripe payment integration",
      "Order management system",
      "User accounts and order history",
      "Admin dashboard",
      "Email notifications",
      "Inventory tracking",
    ],
    learningResources: [
      {
        title: "Stripe Integration Guide",
        url: "https://stripe.com/docs/payments/accept-a-payment",
        type: "docs",
        provider: "Stripe",
      },
      {
        title: "E-commerce Best Practices",
        url: "https://www.shopify.com/blog/ecommerce-website-design",
        type: "article",
        provider: "Shopify",
      },
    ],
  },
  {
    id: "fallback-ci-cd-pipeline",
    name: "CI/CD Pipeline Setup",
    description:
      "Set up a complete CI/CD pipeline with automated testing, deployment, and monitoring. Learn DevOps practices and infrastructure as code.",
    techStack: [
      "GitHub Actions",
      "Docker",
      "Kubernetes",
      "Terraform",
      "Prometheus",
    ],
    difficulty: "advanced",
    timeEstimate: "2-3 weeks",
    skillsTaught: [
      "Continuous Integration",
      "Continuous Deployment",
      "Containerization",
      "Orchestration",
      "Infrastructure as Code",
      "Monitoring & Logging",
    ],
    category: "devops",
    features: [
      "Automated testing on pull requests",
      "Docker containerization",
      "Kubernetes deployment",
      "Infrastructure provisioning with Terraform",
      "Monitoring with Prometheus and Grafana",
      "Automated rollbacks",
      "Secret management",
    ],
    learningResources: [
      {
        title: "GitHub Actions Documentation",
        url: "https://docs.github.com/en/actions",
        type: "docs",
        provider: "GitHub",
      },
      {
        title: "Docker Getting Started",
        url: "https://docs.docker.com/get-started/",
        type: "tutorial",
        provider: "Docker",
      },
    ],
  },
  {
    id: "fallback-weather-app",
    name: "Weather Dashboard",
    description:
      "Build a weather dashboard that fetches data from external APIs, displays forecasts, and saves favorite locations. Learn API integration and data visualization.",
    techStack: ["React", "TypeScript", "Chart.js", "OpenWeather API"],
    difficulty: "beginner",
    timeEstimate: "1 week",
    skillsTaught: [
      "API Integration",
      "Data Visualization",
      "Geolocation",
      "Local Storage",
      "Error Handling",
    ],
    category: "frontend",
    features: [
      "Current weather display",
      "5-day forecast",
      "Location search and geolocation",
      "Favorite locations",
      "Weather charts and graphs",
      "Unit conversion (Celsius/Fahrenheit)",
      "Weather alerts",
    ],
    learningResources: [
      {
        title: "OpenWeather API Documentation",
        url: "https://openweathermap.org/api",
        type: "docs",
        provider: "OpenWeather",
      },
      {
        title: "Chart.js Guide",
        url: "https://www.chartjs.org/docs/latest/",
        type: "docs",
        provider: "Chart.js",
      },
    ],
  },
  {
    id: "fallback-blog-cms",
    name: "Headless CMS Blog",
    description:
      "Create a blog platform with a headless CMS, markdown support, and SEO optimization. Learn content management and static site generation.",
    techStack: ["Next.js", "Contentful", "MDX", "TypeScript", "Vercel"],
    difficulty: "intermediate",
    timeEstimate: "2 weeks",
    skillsTaught: [
      "Headless CMS Integration",
      "Static Site Generation",
      "MDX Processing",
      "SEO Optimization",
      "Content Modeling",
    ],
    category: "fullstack",
    features: [
      "Contentful CMS integration",
      "MDX blog posts with syntax highlighting",
      "Tag and category filtering",
      "Search functionality",
      "RSS feed generation",
      "Social media sharing",
      "Comment system",
      "SEO optimization",
    ],
    learningResources: [
      {
        title: "Contentful Documentation",
        url: "https://www.contentful.com/developers/docs/",
        type: "docs",
        provider: "Contentful",
      },
      {
        title: "Next.js Blog Tutorial",
        url: "https://nextjs.org/learn/basics/create-nextjs-app",
        type: "tutorial",
        provider: "Next.js",
      },
    ],
  },
  {
    id: "fallback-mobile-app",
    name: "React Native Mobile App",
    description:
      "Build a cross-platform mobile app with React Native. Learn mobile development, native features, and app deployment.",
    techStack: ["React Native", "Expo", "TypeScript", "Firebase"],
    difficulty: "intermediate",
    timeEstimate: "3-4 weeks",
    skillsTaught: [
      "Mobile Development",
      "Native Features",
      "Push Notifications",
      "Offline Support",
      "App Store Deployment",
    ],
    category: "mobile",
    features: [
      "Cross-platform iOS and Android app",
      "Native navigation",
      "Camera and photo library access",
      "Push notifications",
      "Offline data persistence",
      "Biometric authentication",
      "App store deployment",
    ],
    learningResources: [
      {
        title: "React Native Documentation",
        url: "https://reactnative.dev/docs/getting-started",
        type: "docs",
        provider: "React Native",
      },
      {
        title: "Expo Guide",
        url: "https://docs.expo.dev/",
        type: "docs",
        provider: "Expo",
      },
    ],
  },
  {
    id: "fallback-graphql-api",
    name: "GraphQL API Server",
    description:
      "Build a GraphQL API with subscriptions, authentication, and data loaders. Learn modern API design and real-time data fetching.",
    techStack: ["Node.js", "Apollo Server", "GraphQL", "PostgreSQL", "Redis"],
    difficulty: "advanced",
    timeEstimate: "3 weeks",
    skillsTaught: [
      "GraphQL Schema Design",
      "Resolvers and Data Loaders",
      "Subscriptions",
      "Authentication",
      "Caching Strategies",
      "N+1 Problem Solutions",
    ],
    category: "backend",
    features: [
      "GraphQL schema with types and queries",
      "Mutations for data modification",
      "Real-time subscriptions",
      "Authentication and authorization",
      "DataLoader for batching",
      "Redis caching",
      "GraphQL Playground",
    ],
    learningResources: [
      {
        title: "Apollo Server Documentation",
        url: "https://www.apollographql.com/docs/apollo-server/",
        type: "docs",
        provider: "Apollo",
      },
      {
        title: "GraphQL Best Practices",
        url: "https://graphql.org/learn/best-practices/",
        type: "docs",
        provider: "GraphQL",
      },
    ],
  },
  {
    id: "fallback-data-dashboard",
    name: "Analytics Dashboard",
    description:
      "Create an interactive analytics dashboard with charts, filters, and real-time updates. Learn data visualization and dashboard design.",
    techStack: ["React", "TypeScript", "D3.js", "Recharts", "WebSocket"],
    difficulty: "intermediate",
    timeEstimate: "2-3 weeks",
    skillsTaught: [
      "Data Visualization",
      "Dashboard Design",
      "Real-time Updates",
      "Complex Filtering",
      "Performance Optimization",
    ],
    category: "frontend",
    features: [
      "Multiple chart types (line, bar, pie, scatter)",
      "Interactive filters and date ranges",
      "Real-time data updates",
      "Export to CSV/PDF",
      "Responsive grid layout",
      "Custom metrics and KPIs",
      "Drill-down capabilities",
    ],
    learningResources: [
      {
        title: "D3.js Documentation",
        url: "https://d3js.org/",
        type: "docs",
        provider: "D3",
      },
      {
        title: "Dashboard Design Patterns",
        url: "https://www.nngroup.com/articles/dashboard-design/",
        type: "article",
        provider: "Nielsen Norman Group",
      },
    ],
  },
  {
    id: "fallback-auth-system",
    name: "Authentication System",
    description:
      "Build a complete authentication system with OAuth, 2FA, and session management. Learn security best practices and user management.",
    techStack: ["Node.js", "Passport.js", "JWT", "Redis", "PostgreSQL"],
    difficulty: "intermediate",
    timeEstimate: "2 weeks",
    skillsTaught: [
      "Authentication Strategies",
      "OAuth Integration",
      "Two-Factor Authentication",
      "Session Management",
      "Security Best Practices",
    ],
    category: "backend",
    features: [
      "Email/password authentication",
      "OAuth with Google, GitHub, Facebook",
      "Two-factor authentication (TOTP)",
      "Password reset flow",
      "Session management with Redis",
      "Rate limiting",
      "Account verification",
      "Security headers and CSRF protection",
    ],
    learningResources: [
      {
        title: "Passport.js Documentation",
        url: "http://www.passportjs.org/docs/",
        type: "docs",
        provider: "Passport",
      },
      {
        title: "OWASP Authentication Cheat Sheet",
        url: "https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html",
        type: "docs",
        provider: "OWASP",
      },
    ],
  },
];
